apiVersion: apps/v1
kind: Deployment
metadata:
  name: newords-go-be-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newords-go-be
  template:
    metadata:
      labels:
        app: newords-go-be
    spec:
      containers:
      - name: newords-go-be
        image: asas00/newords-go-be:latest # This will be replaced in the GitHub Actions pipeline
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: newords-go-be-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8090
  selector:
    app: newords-go-be