apiVersion: apps/v1
kind: Deployment
metadata:
  name: newordsbe-digistar-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newordsbe-digistar
  template:
    metadata:
      labels:
        app: newordsbe-digistar
    spec:
      containers:
      - name: newordsbe-digistar
        image: asas00/newordsbe-digistar:latest # This will be replaced in the GitHub Actions pipeline
        ports:
        - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: newordsbe-digistar-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8099
  selector:
    app: newordsbe-digistar